### ISSUE TITLE
Spaces in file names and paths cause errors

### ISSUE THREAD

**Issue by mattzuba** [yan-foto/electron-pug#5]
Since the getPath function uses the parse() method of the URL library, [it will convert spaces in file paths to %20](https://nodejs.org/api/url.html#url_escaped_characters).  When fs.readFileSync receives the modified file name, it will fail to load the file properly which throws an error.

While this probably isn't an issue on *Nix machines, on Windows, where an Electron App would be installed in 'Program Files' or 'Program Files (x86)', it becomes an issue.

**Comment by yan-foto** [comment]
Since spaces are not allowed in URLs, they [should](https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/) be percent encoded. Could you verify if `readFile` works properly with paths containing spaces on a windows machine?

In any case I think `decodeURIComponent` can save the situation!

**Comment by mattzuba** [comment]
It fails with `readFile` as well.  I tested the stock nodejs (as opposed to Electron's modified lib) `fs.readFile` and `fs.readFileSync` and they also fail to work with %20 in paths.

```
C:\Users\mzuba\Documents\misc>node
> fs.readFileSync('my test/app.asar')
<Buffer 04 00 00 00 60 ca 01 00 5c ca 01 00 58 ca 01 00 7b 22 66 69 6c 65 73 22 3a 7b 22 61 70 70 2e 6a 73 22 3a 7b 22 73 69 7a 65 22 3a 32 36 38 2c 22 6f 66 ... >
> fs.readFileSync('my%20test/app.asar')
Error: ENOENT: no such file or directory, open 'C:\Users\mzuba\Documents\misc\my%20test\app.asar'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
>
```

**Comment by yan-foto** [comment]
Not the encoded path, but with actual spaces!

**Comment by mattzuba** [comment]
I amended the code block with a test with spaces and one encoded.  With spaces worked, encoded failed.

**Comment by yan-foto** [comment]
Thank you :+1: I will start patching it now.

**Comment by yan-foto** [comment]
I just published version `1.5.1` which should fix the problem.

**Comment by mattzuba** [comment]
That seems to have solved it, thanks!

**Comment by yan-foto** [comment]
Thanks for reporting!
